import type { VocabCategory, VocabEntry } from "./vocabulary.types";

function v(
  key: string,
  es: string,
  category: VocabCategory,
  example?: string,
): VocabEntry {
  return { key, en: key, es, category, example };
}

/** Diccionario A1 — ficha cole + lectura Tom + cheatsheet Rodri. */
export const ENGLISH_A1_VOCABULARY: Record<string, VocabEntry> = {
  // ── Saludos y cortesía ──
  hello: v("hello", "hola", "greetings"),
  hi: v("hi", "hola (informal)", "greetings"),
  "good morning": v("good morning", "buenos días", "greetings"),
  "good afternoon": v("good afternoon", "buenas tardes", "greetings"),
  "good night": v("good night", "buenas noches", "greetings"),
  "good evening": v("good evening", "buenas tardes/noches", "greetings"),
  "see you later": v("see you later", "hasta luego", "greetings"),
  please: v("please", "por favor", "greetings"),
  "thank you": v("thank you", "gracias", "greetings"),
  thanks: v("thanks", "gracias", "greetings"),
  "you're welcome": v("you're welcome", "de nada", "greetings"),
  sorry: v("sorry", "perdón / lo siento", "greetings"),
  "nice to meet you": v("nice to meet you", "encantado / mucho gusto", "greetings"),
  goodbye: v("goodbye", "adiós", "greetings"),

  // ── Gramática / wh- ──
  who: v("who", "quién", "grammar"),
  what: v("what", "qué", "grammar"),
  when: v("when", "cuándo", "grammar"),
  where: v("where", "dónde", "grammar"),
  which: v("which", "cuál", "grammar"),
  why: v("why", "por qué", "grammar"),
  how: v("how", "cómo", "grammar"),
  always: v("always", "siempre", "grammar"),
  usually: v("usually", "normalmente", "grammar"),
  often: v("often", "a menudo", "grammar"),
  sometimes: v("sometimes", "a veces", "grammar"),
  never: v("never", "nunca", "grammar"),
  "every day": v("every day", "cada día", "grammar"),
  "every week": v("every week", "cada semana", "grammar"),
  "once a week": v("once a week", "una vez por semana", "grammar"),
  yesterday: v("yesterday", "ayer", "time"),
  tomorrow: v("tomorrow", "mañana", "time"),
  today: v("today", "hoy", "time"),
  now: v("now", "ahora", "time"),
  "right now": v("right now", "ahora mismo", "time"),
  "at the moment": v("at the moment", "en este momento", "time"),
  currently: v("currently", "actualmente", "time"),
  "in the morning": v("in the morning", "por la mañana", "time"),

  // ── To be / pronombres ──
  am: v("am", "soy/estoy (I am)", "grammar"),
  is: v("is", "es/está (he/she/it)", "grammar"),
  are: v("are", "son/están (you/we/they)", "grammar"),
  active: v("active", "activo", "other"),
  serious: v("serious", "serio", "other"),
  shy: v("shy", "tímido", "other"),
  talkative: v("talkative", "hablador", "other"),
  happy: v("happy", "feliz / contento", "other"),
  sad: v("sad", "triste", "other"),
  tired: v("tired", "cansado", "other"),
  hungry: v("hungry", "con hambre", "other"),
  thirsty: v("thirsty", "con sed", "other"),
  late: v("late", "tarde", "time"),
  ready: v("ready", "listo", "other"),
  ok: v("ok", "bien / vale", "other"),

  // ── Verbos comunes ──
  play: v("play", "jugar", "verbs", "I play football."),
  plays: v("plays", "juega (he/she)", "verbs"),
  playing: v("playing", "jugando (-ing)", "verbs"),
  like: v("like", "gustar", "verbs"),
  likes: v("likes", "gusta (he/she)", "verbs"),
  love: v("love", "amar / encantar", "verbs"),
  loves: v("loves", "ama (he/she)", "verbs"),
  want: v("want", "querer", "verbs"),
  wants: v("wants", "quiere (he/she)", "verbs"),
  have: v("have", "tener", "verbs"),
  has: v("has", "tiene (he/she)", "verbs"),
  do: v("do", "hacer / auxiliar", "verbs"),
  does: v("does", "hace / auxiliar (he/she)", "verbs"),
  go: v("go", "ir", "verbs"),
  goes: v("goes", "va (he/she)", "verbs"),
  went: v("went", "fue/fui (pasado de go)", "verbs"),
  get: v("get", "obtener / levantarse", "verbs"),
  gets: v("gets", "obtiene / se levanta", "verbs"),
  "get up": v("get up", "levantarse", "verbs"),
  watch: v("watch", "mirar / ver", "verbs", "I watch TV."),
  watches: v("watches", "mira (he/she)", "verbs"),
  work: v("work", "trabajar", "verbs"),
  study: v("study", "estudiar", "verbs"),
  studies: v("studies", "estudia", "verbs"),
  eat: v("eat", "comer", "verbs"),
  eats: v("eats", "come", "verbs"),
  drink: v("drink", "beber", "verbs"),
  drinks: v("drinks", "bebe", "verbs"),
  read: v("read", "leer", "verbs"),
  reads: v("reads", "lee", "verbs"),
  write: v("write", "escribir", "verbs"),
  run: v("run", "correr", "verbs"),
  running: v("running", "corriendo", "verbs"),
  swimming: v("swimming", "nadando / natación", "sport"),
  cook: v("cook", "cocinar", "verbs"),
  meet: v("meet", "conocer / quedar", "verbs"),
  live: v("live", "vivir", "verbs"),
  lives: v("lives", "vive", "verbs"),
  rise: v("rise", "salir / levantarse", "verbs"),
  rises: v("rises", "sale (sol)", "verbs"),
  boil: v("boil", "hervir", "verbs"),
  boils: v("boils", "hierve", "verbs"),
  prefer: v("prefer", "preferir", "verbs"),
  help: v("help", "ayudar", "verbs"),
  helping: v("helping", "ayudando", "verbs"),
  listening: v("listening", "escuchando", "verbs"),
  reading: v("reading", "leyendo", "verbs"),
  eating: v("eating", "comiendo", "verbs"),

  // ── Present simple vocab ──
  spinach: v("spinach", "espinacas", "food"),
  broccoli: v("broccoli", "brócoli", "food"),
  pizza: v("pizza", "pizza", "food"),
  fish: v("fish", "pescado", "food"),
  chocolate: v("chocolate", "chocolate", "food"),
  pasta: v("pasta", "pasta", "food"),
  fruit: v("fruit", "fruta", "food"),
  vegetables: v("vegetables", "verduras", "food"),
  breakfast: v("breakfast", "desayuno", "food"),
  lunch: v("lunch", "comida / almuerzo", "food"),
  dinner: v("dinner", "cena", "food"),
  bread: v("bread", "pan", "food"),
  sandwich: v("sandwich", "bocadillo", "food"),
  "ice cream": v("ice cream", "helado", "food"),
  apple: v("apple", "manzana", "food"),
  juice: v("juice", "zumo", "food"),
  water: v("water", "agua", "food"),
  coffee: v("coffee", "café", "food"),

  // ── Tom's day (lectura PDF) ──
  tom: v("tom", "Tom (nombre)", "other"),
  manchester: v("manchester", "Mánchester", "other"),
  england: v("england", "Inglaterra", "other"),
  monday: v("monday", "lunes", "time"),
  friday: v("friday", "viernes", "time"),
  saturday: v("saturday", "sábado", "time"),
  sunday: v("sunday", "domingo", "time"),
  comics: v("comics", "cómics", "other"),
  "video games": v("video games", "videojuegos", "sport"),
  friends: v("friends", "amigos", "family"),
  "best friend": v("best friend", "mejor amigo", "family"),
  family: v("family", "familia", "family"),
  bed: v("bed", "cama", "other"),
  routine: v("routine", "rutina", "other"),
  habit: v("habit", "hábito", "other"),
  facts: v("facts", "hechos", "grammar"),
  truth: v("truth", "verdad", "grammar"),

  // ── Cole / escuela ──
  school: v("school", "colegio", "school"),
  teacher: v("teacher", "profesor/a", "school"),
  classroom: v("classroom", "clase / aula", "school"),
  homework: v("homework", "deberes", "school"),
  exam: v("exam", "examen", "school"),
  break: v("break", "recreo / descanso", "school"),
  playground: v("playground", "patio", "school"),
  maths: v("maths", "mates", "school"),
  english: v("english", "inglés", "school"),
  student: v("student", "estudiante / alumno", "school"),
  students: v("students", "estudiantes", "school"),

  // ── Familia ──
  mum: v("mum", "mamá (UK)", "family"),
  mother: v("mother", "madre", "family"),
  dad: v("dad", "papá", "family"),
  father: v("father", "padre", "family"),
  brother: v("brother", "hermano", "family"),
  sister: v("sister", "hermana", "family"),
  grandma: v("grandma", "abuela", "family"),
  grandpa: v("grandpa", "abuelo", "family"),
  cousin: v("cousin", "primo/a", "family"),

  // ── Deporte ──
  football: v("football", "fútbol (UK)", "sport"),
  soccer: v("soccer", "fútbol (US)", "sport"),
  basketball: v("basketball", "baloncesto", "sport"),
  tennis: v("tennis", "tenis", "sport"),
  bike: v("bike", "bici", "sport"),
  cycling: v("cycling", "ciclismo", "sport"),
  goal: v("goal", "gol / portería", "sport"),
  team: v("team", "equipo", "sport"),
  win: v("win", "ganar", "sport"),
  sport: v("sport", "deporte", "sport"),

  // ── Animales ──
  dog: v("dog", "perro", "animals"),
  cat: v("cat", "gato", "animals"),
  shark: v("shark", "tiburón", "animals"),
  dinosaur: v("dinosaur", "dinosaurio", "animals"),
  snake: v("snake", "serpiente", "animals"),
  horse: v("horse", "caballo", "animals"),
  dolphin: v("dolphin", "delfín", "animals"),
  eagle: v("eagle", "águila", "animals"),

  // ── Colores ──
  red: v("red", "rojo", "colors"),
  blue: v("blue", "azul", "colors"),
  green: v("green", "verde", "colors"),
  yellow: v("yellow", "amarillo", "colors"),
  orange: v("orange", "naranja", "colors"),
  purple: v("purple", "morado", "colors"),
  black: v("black", "negro", "colors"),
  white: v("white", "blanco", "colors"),
  grey: v("grey", "gris", "colors"),
  colour: v("colour", "color (UK)", "colors"),
  color: v("color", "color (US)", "colors"),

  // ── Tiempo / clima ──
  sunny: v("sunny", "soleado", "time"),
  rainy: v("rainy", "lluvioso", "time"),
  cold: v("cold", "frío", "time"),
  hot: v("hot", "calor / caliente", "time"),
  weather: v("weather", "tiempo (clima)", "time"),
  sun: v("sun", "sol", "time"),
  east: v("east", "este", "other"),
  madrid: v("madrid", "Madrid", "other"),
  spain: v("spain", "España", "other"),

  // ── Tech ──
  tablet: v("tablet", "tablet", "other"),
  phone: v("phone", "móvil", "other"),
  computer: v("computer", "ordenador", "other"),
  controller: v("controller", "mando", "other"),
  level: v("level", "nivel", "other"),

  // ── Números ──
  one: v("one", "uno", "other"),
  two: v("two", "dos", "other"),
  three: v("three", "tres", "other"),
  ten: v("ten", "diez", "other"),

  // ── Otros útiles ──
  hobby: v("hobby", "afición / hobby", "other"),
  hobbies: v("hobbies", "aficiones", "other"),
  park: v("park", "parque", "other"),
  bus: v("bus", "autobús", "other"),
  piano: v("piano", "piano", "other"),
  music: v("music", "música", "other"),
  books: v("books", "libros", "school"),
  book: v("book", "libro", "school"),
  paula: v("paula", "Paula (nombre)", "other"),
};

export const ENGLISH_A1_VOCAB_LIST: VocabEntry[] = Object.values(
  ENGLISH_A1_VOCABULARY,
).sort((a, b) => a.key.localeCompare(b.key));

export function lookupVocabulary(raw: string): VocabEntry | null {
  const key = raw.trim().toLowerCase();
  return ENGLISH_A1_VOCABULARY[key] ?? null;
}

export function getSortedVocabKeys(): string[] {
  return Object.keys(ENGLISH_A1_VOCABULARY).sort((a, b) => b.length - a.length);
}
